### ISSUE TITLE
Definir as cenas de jogo

### ISSUE THREAD

**Issue by melaoroliso** [ARMBREAKERS-GAMES/Gatasma#20]
Telas de abertura e encerramento, cenas do jogo e outros. Usar fluxogramas para representar as ações dos personagens. Depende de https://github.com/ARMBREAKERS-GAMES/Gatasma/issues/3

**Comment by melaoroliso** [comment]
Telas de abertura e encerramento, cenas do jogo e outros. Usar fluxogramas para representar as ações dos personagens. Depende de https://github.com/boidacarapreta/adcipt20232/issues/3.

**Comment by Guglevers** [comment]
feito, o fluxograma foi feito a mão no papel.
