### ISSUE TITLE
Programar o(s) mapa(s) do jogo

### ISSUE THREAD

**Issue by melaoroliso** [ARMBREAKERS-GAMES/Gatasma#24]
- [x] Criar tiles personalizados;
- [x] Definir as camadas;
- [x]  Dispor os tiles nas camadas.
- [x]  Parametrizar o mapa;
- [x]  Exportar o mapa;
- [x]  Importar o mapa e suas camadas no jogo.
Referências: aplicativo [Tiled](https://www.mapeditor.org/) para edição do mapa em formato JSON e [OpenGameArt](https://opengameart.org/). Depende de #23

**Comment by Guglevers** [comment]
Feito.
