### ISSUE TITLE
Definir os personagens e objetos interativos

### ISSUE THREAD

**Issue by melaoroliso** [ARMBREAKERS-GAMES/Gatasma#25]
Desenhar personagens e objetos interativos. Depende de #3

**Comment by Guglevers** [comment]
![Image](https://github.com/ARMBREAKERS-GAMES/Gatasma/assets/141068211/f2cdbbc2-1b8b-49a6-a555-9c0f6bb1b4c8)



![Image](https://github.com/ARMBREAKERS-GAMES/Gatasma/assets/141068211/9cee08ba-103f-4ca5-901b-1eed84f83436)

**Comment by Guglevers** [comment]
o jogo vai ter paredes atravessáveis e alavancas.
